version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_NAME: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - todolist_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      timeout: 5s
      interval: 5s
      retries:
        5
  migrations:
    image: vladosik11/todolist_diploma_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: db
    command: python manage.py migrate

  api:
      image: vladosik11/todolist_diploma_work:$GITHUB_REF_NAME-$GITHUB_RUN_ID
      restart: always
      env_file: .env
      environment:
        DB_HOST: db
      depends_on:
        db:
          condition: service_healthy
        migrations:
          condition: service_completed_successfully
      ports:
        - "8000:8000"

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      api:
        condition: service_started
    ports:
      - "80:80"

volumes:
  todolist_data: