# Generated by Django 4.2.2 on 2023-07-18 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={},
        ),
        migrations.AlterModelOptions(
            name="boardparticipant",
            options={},
        ),
        migrations.AddField(
            model_name="goalcategory",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="goals.board",
            ),
        ),
        migrations.AlterField(
            model_name="boardparticipant",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to="goals.board",
            ),
        ),
        migrations.AlterField(
            model_name="boardparticipant",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Владелец"), (2, "Редактор"), (3, "Читатель")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="boardparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
